// Code generated by MockGen. DO NOT EDIT.
// Source: router.go
//
// Generated by this command:
//
//	mockgen -source=router.go -destination=./mocks/mock_userservice.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
