version: "3"

dotenv:
  - .env

vars:
  APP_PACKAGE: ./cmd/app
  BINARY_DIR: bin
  ARCHIVES_DIR: archives
  BINARY_NAME: app
  BINARY_PATH: "{{.BINARY_DIR}}/{{.BINARY_NAME}}"

tasks:
  default:
    desc: Show help information
    deps:
      - help

  help:
    desc: List available tasks
    silent: true
    cmds:
      - task --list

  fmt:
    desc: Format Go source files
    cmds:
      - go fmt ./...

  tidy:
    desc: Tidy module dependencies
    cmds:
      - go mod tidy

  test:
    desc: Run all Go tests
    cmds:
      - gotestsum ./...

  build:
    desc: Build the application binary
    deps:
      - fmt
    cmds:
      - mkdir -p {{.BINARY_DIR}}
      - go build -o {{.BINARY_PATH}} {{.APP_PACKAGE}}

  run:
    desc: Run the built application (expects database connectivity)
    deps:
      - build
    cmds:
      - ./{{.BINARY_PATH}}

  generate:
    desc: Generate mocks
    cmds:
      - go generate ./...

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BINARY_DIR}}

  "dev:up":
    desc: Start the Docker development stack (db, migrations, backend)
    cmds:
      - docker compose up --build

  "dev:down":
    desc: Stop the Docker stack and remove containers
    cmds:
      - docker compose down

  "migrations":
    desc: Run all migrations
    cmds:
      - docker compose down -v
      - docker compose run migrate

  "enter-postgres":
    desc: Enter the Postgres container's psql shell
    cmds:
      - docker compose exec db psql -U ${POSTGRES_USER} -d ${POSTGRES_DB}

  "debug-tc-db":
    desc: Debug testcontainer postgresql
    cmds:
      - docker exec -it $(docker ps | awk '$2=="postgres:16-alpine" {print $1}') psql -U user -d db

  "db:clean":
    desc: Clean the database (truncate all tables and repopulate roles)
    cmds:
      - go run ./scripts/clean/main.go

  "db:generate":
    desc: Generate test data in the database
    cmds:
      - go run ./scripts/benchmark/main.go -traffic -users 200 -events 1000 -registrations 10000 -concurrency 20

  "db:bench":
    desc: Run database benchmarks with memory stats
    cmds:
      - go test -run=^$ -bench=. -count 10 -benchmem ./test/integral/
