// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kapiw04/convenly/internal/domain/event (interfaces: EventRepo)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_eventrepo.go -package mock_event . EventRepo
//

// Package mock_event is a generated GoMock package.
package mock_event

import (
	reflect "reflect"

	event "github.com/kapiw04/convenly/internal/domain/event"
	gomock "go.uber.org/mock/gomock"
)

// MockEventRepo is a mock of EventRepo interface.
type MockEventRepo struct {
	ctrl     *gomock.Controller
	recorder *MockEventRepoMockRecorder
	isgomock struct{}
}

// MockEventRepoMockRecorder is the mock recorder for MockEventRepo.
type MockEventRepoMockRecorder struct {
	mock *MockEventRepo
}

// NewMockEventRepo creates a new mock instance.
func NewMockEventRepo(ctrl *gomock.Controller) *MockEventRepo {
	mock := &MockEventRepo{ctrl: ctrl}
	mock.recorder = &MockEventRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventRepo) EXPECT() *MockEventRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockEventRepo) Delete(eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockEventRepoMockRecorder) Delete(eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockEventRepo)(nil).Delete), eventID)
}

// FindAll mocks base method.
func (m *MockEventRepo) FindAll() ([]*event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll")
	ret0, _ := ret[0].([]*event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockEventRepoMockRecorder) FindAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockEventRepo)(nil).FindAll))
}

// FindAllByTags mocks base method.
func (m *MockEventRepo) FindAllByTags(tagNames []string) ([]*event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByTags", tagNames)
	ret0, _ := ret[0].([]*event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByTags indicates an expected call of FindAllByTags.
func (mr *MockEventRepoMockRecorder) FindAllByTags(tagNames any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByTags", reflect.TypeOf((*MockEventRepo)(nil).FindAllByTags), tagNames)
}

// FindAllWithFilters mocks base method.
func (m *MockEventRepo) FindAllWithFilters(filter *event.EventFilter) ([]*event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllWithFilters", filter)
	ret0, _ := ret[0].([]*event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllWithFilters indicates an expected call of FindAllWithFilters.
func (mr *MockEventRepoMockRecorder) FindAllWithFilters(filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllWithFilters", reflect.TypeOf((*MockEventRepo)(nil).FindAllWithFilters), filter)
}

// FindAttendingEvents mocks base method.
func (m *MockEventRepo) FindAttendingEvents(userID string, pagination *event.Pagination) ([]*event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAttendingEvents", userID, pagination)
	ret0, _ := ret[0].([]*event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAttendingEvents indicates an expected call of FindAttendingEvents.
func (mr *MockEventRepoMockRecorder) FindAttendingEvents(userID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAttendingEvents", reflect.TypeOf((*MockEventRepo)(nil).FindAttendingEvents), userID, pagination)
}

// FindByID mocks base method.
func (m *MockEventRepo) FindByID(arg0 string) (*event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0)
	ret0, _ := ret[0].(*event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockEventRepoMockRecorder) FindByID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockEventRepo)(nil).FindByID), arg0)
}

// FindByOrganizer mocks base method.
func (m *MockEventRepo) FindByOrganizer(userID string, pagination *event.Pagination) ([]*event.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByOrganizer", userID, pagination)
	ret0, _ := ret[0].([]*event.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByOrganizer indicates an expected call of FindByOrganizer.
func (mr *MockEventRepoMockRecorder) FindByOrganizer(userID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByOrganizer", reflect.TypeOf((*MockEventRepo)(nil).FindByOrganizer), userID, pagination)
}

// GetAttendees mocks base method.
func (m *MockEventRepo) GetAttendees(eventID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttendees", eventID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttendees indicates an expected call of GetAttendees.
func (mr *MockEventRepoMockRecorder) GetAttendees(eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttendees", reflect.TypeOf((*MockEventRepo)(nil).GetAttendees), eventID)
}

// GetAttendeesCount mocks base method.
func (m *MockEventRepo) GetAttendeesCount(eventID string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttendeesCount", eventID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttendeesCount indicates an expected call of GetAttendeesCount.
func (mr *MockEventRepoMockRecorder) GetAttendeesCount(eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttendeesCount", reflect.TypeOf((*MockEventRepo)(nil).GetAttendeesCount), eventID)
}

// IsUserAttending mocks base method.
func (m *MockEventRepo) IsUserAttending(userID, eventID string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsUserAttending", userID, eventID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsUserAttending indicates an expected call of IsUserAttending.
func (mr *MockEventRepoMockRecorder) IsUserAttending(userID, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsUserAttending", reflect.TypeOf((*MockEventRepo)(nil).IsUserAttending), userID, eventID)
}

// RegisterAttendance mocks base method.
func (m *MockEventRepo) RegisterAttendance(userID, eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterAttendance", userID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterAttendance indicates an expected call of RegisterAttendance.
func (mr *MockEventRepoMockRecorder) RegisterAttendance(userID, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterAttendance", reflect.TypeOf((*MockEventRepo)(nil).RegisterAttendance), userID, eventID)
}

// RemoveAttendance mocks base method.
func (m *MockEventRepo) RemoveAttendance(userID, eventID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAttendance", userID, eventID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAttendance indicates an expected call of RemoveAttendance.
func (mr *MockEventRepoMockRecorder) RemoveAttendance(userID, eventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAttendance", reflect.TypeOf((*MockEventRepo)(nil).RemoveAttendance), userID, eventID)
}

// Save mocks base method.
func (m *MockEventRepo) Save(arg0 *event.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockEventRepoMockRecorder) Save(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockEventRepo)(nil).Save), arg0)
}
